### PR TITLE
Allow sliding on render indicator (ball indicator)

### PR DESCRIPTION
**Pull request by rawtechnologies**

### CODE REVIEW

**Comment by blazk0** [comment]
When can this be merged ?

**Comment by rawtechnologies** [comment]
In a separate PR I'm going to add multitouch support so we can use multiple vertical sliders at the same time. The current approach does not support two sliders operating at the same time. That will be a new branch / new PR.

**Comment by rawtechnologies** [comment]
@blazk0 in the meantime while I wait for this to merge I'm using:
`yarn add https://github.com/rawtechnologies/rn-vertical-slider`

You could do the same off my repo or you could fork and use your repo for safety until this is merged.

**Comment by sacmii** [comment]
**Cannot merge since code changed:**

The reason for this is that the code has been updated to use a new version of a library. This change has resulted in some conflicts with the existing code, preventing the merge from being completed.

Please review the changes to ensure they are compatible with the rest of the codebase before attempting to merge again.

**Pull request closed without merging**
